# Generated by Django 4.1.7 on 2024-01-15 18:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "airport_service",
            "0002_rename_closet_big_city_airport_closest_big_city_and_more",
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="airport",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="airport",
            constraint=models.UniqueConstraint(
                fields=("name", "closest_big_city"),
                name="unique_airport_name_closest_big_city",
            ),
        ),
    ]
