# Generated by Django 4.1.7 on 2024-01-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("airport_service", "0003_alter_airport_unique_together_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="crew",
            constraint=models.UniqueConstraint(
                fields=("first_name", "last_name"),
                name="unique_crew_first_name_last_name",
            ),
        ),
    ]
